### ISSUE TITLE
Run the agent for a week and see if it keeps itself authenticated or not

### ISSUE THREAD

**Issue by chrisjohnson** [chrisjohnson/azure-key-vault-agent#12]
IF not, figure out how to force re-auth

**Comment by markercm** [comment]
I am trying this on a test server with a checking frequency of 1h.  Started 01-15-20 at 11:30am EST.

**Comment by markercm** [comment]
This worked great for a week, no issues.  May want to re-test later on as well.

**Comment by chrisjohnson** [comment]
I think we can close this, the biggest concern was that the auth code will be able to keep a connection alive, and the auth code is basically copy/pasted from azure's SDK examples. I can't imagine we have any plans to change it in any way.
