### ISSUE TITLE
On config change, possibly handle path changes

### ISSUE THREAD

**Issue by chrisjohnson** [chrisjohnson/azure-key-vault-agent#13]
If the target path changes, do we orphan the old path? Do we delete it? Should we just log the change and move on?

**Comment by grep-ir** [comment]
I vote we keep it simple and just orphan the old path.

**Comment by markercm** [comment]
So if we just orphan the file, do we want to log that the Path changed, or are we okay with just the generic config file changed message?

**Comment by grep-ir** [comment]
in the sinkworker write() function we log what path is being written to.  That should be sufficient for someone consuming the logs to figure out that it is different than before.
